# Generated by Django 5.0.6 on 2024-06-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="position_id",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="position_name"),
                ),
                (
                    "riskLevel",
                    models.SmallIntegerField(verbose_name="position_risk_level"),
                ),
                (
                    "minimumSalary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=11,
                        verbose_name="position_minimum_salary",
                    ),
                ),
                (
                    "maximumSalary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=11,
                        verbose_name="position_maximum_salary",
                    ),
                ),
            ],
        ),
    ]
