# Generated by Django 5.0.6 on 2024-06-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="id",
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="position_id",
            ),
        ),
    ]
