# Generated by Django 4.2.14 on 2024-08-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='photo_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='photo_url'),
        ),
    ]
