# Generated by Django 5.0.6 on 2024-06-07 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("positions", "0003_rename_maximumsalary_position_maximum_salary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="income_id",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="income_name")),
                (
                    "depend_on_salary",
                    models.BooleanField(verbose_name="depend_on_salary"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Habilitada", "Enabled"),
                            ("Deshabilitada", "Disabled"),
                        ],
                        default="Habilitada",
                        max_length=20,
                        verbose_name="income_state",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positions.position",
                        verbose_name="position",
                    ),
                ),
            ],
        ),
    ]
