# Generated by Django 5.0.6 on 2024-06-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incomes", "0001_initial"),
        ("positions", "0003_rename_maximumsalary_position_maximum_salary_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="income",
            name="position",
        ),
        migrations.AddField(
            model_name="income",
            name="positions",
            field=models.ManyToManyField(
                to="positions.position", verbose_name="positions"
            ),
        ),
    ]
