# Generated by Django 4.2.14 on 2024-08-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0003_rename_maximumsalary_position_maximum_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='deduction_id')),
                ('name', models.CharField(max_length=100, verbose_name='deduction_name')),
                ('depend_on_salary', models.BooleanField(verbose_name='depend_on_salary')),
                ('state', models.CharField(choices=[('Habilitada', 'Enabled'), ('Deshabilitada', 'Disabled')], default='Habilitada', max_length=20, verbose_name='deduction_state')),
                ('positions', models.ManyToManyField(to='positions.position', verbose_name='positions')),
            ],
        ),
    ]
