# Generated by Django 5.0.6 on 2024-06-07 00:40

import employees.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="national_id",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[employees.validators.validate_digits],
                verbose_name="national_id",
            ),
        ),
    ]
