# Generated by Django 5.0.6 on 2024-06-07 00:41

import employees.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_alter_employee_national_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="national_id",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[employees.validators.validate_digits],
                verbose_name="national_id",
            ),
        ),
    ]
