# Generated by Django 4.2.14 on 2024-08-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='photo_url'),
        ),
    ]
